services:
  - type: web
    name: smartdocshield
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y tesseract-ocr poppler-utils
      python -m spacy download en_core_web_sm
    startCommand: python backend/app.py